---CREATION OF TABLE FOR PRODUCT
CREATE TABLE PRODUCT_STOCK
(
WINE_NAME VARCHAR2(50) PRIMARY KEY,
WINE_PRICE NUMBER NOT NULL,
WINE_TYPE VARCHAR2(50)NOT NULL,
WINE_QUANTITY NUMBER CHECK (WINE_QUANTITY>0) 
);
/
SELECT * FROM PRODUCT_STOCK;
/
CREATE TABLE VENDOR
(
VD_ID NUMBER PRIMARY KEY,
VD_NAME VARCHAR2(20) NOT NULL,
ADDRESS VARCHAR2(50) NOT NULL,
EMAIL VARCHAR2(50) UNIQUE,
PHONE_NUMBER NUMBER UNIQUE
);
/

----VENDOR-SEQUENCE
CREATE SEQUENCE VEND
INCREMENT BY 1
START WITH 1
MAXVALUE 20
MINVALUE 1
NOCYCLE
NOCACHE;
/

DROP SEQUENCE VEND;
/
SELECT * FROM VENDOR;
/

CREATE TABLE VENDOR_ORDER 
(
VO_ID NUMBER PRIMARY KEY,
WINE_NAME VARCHAR(20) NOT NULL,
ORDER_DATE DATE NOT NULL,
PRICE NUMBER NOT NULL,
QUANTITY NUMBER CHECK(QUANTITY>0)
);
/
SELECT * FROM VENDOR_ORDER;
/
----VENDOR_ORDER-SEQUENCE
CREATE SEQUENCE VEND_ORDER
INCREMENT BY 1
START WITH 1
MAXVALUE 20
MINVALUE 1
NOCYCLE
NOCACHE;
/
DROP SEQUENCE VEND_ORDER;
/
CREATE TABLE ORDER_DETAILS 
(
ORDER_ID NUMBER PRIMARY KEY,
ORDER_DATE DATE NOT NULL,
WINE_NAME VARCHAR2(50),
CONSTRAINT W_NAME FOREIGN KEY(WINE_NAME)REFERENCES PRODUCT_STOCK(WINE_NAME),
WINE_QUANTITY NUMBER CHECK(WINE_QUANTITY>0) 
);

SELECT * FROM ORDER_DETAILS;
/
----VENDOR-SEQUENCE
CREATE SEQUENCE ORD
INCREMENT BY 1
START WITH 1
MAXVALUE 20
MINVALUE 1
NOCYCLE
NOCACHE;
/
DROP SEQUENCE ORD;
/
CREATE TABLE CUSTOMER_PAYMENT
(
P_ID NUMBER PRIMARY KEY,
ORDER_ID NUMBER,
CONSTRAINT C_PAY FOREIGN KEY (ORDER_ID) REFERENCES ORDER_DETAILS(ORDER_ID),
PAYMENT_MODE VARCHAR2(20) NOT NULL,
PAYMENT_DATE DATE NOT NULL
);
/
SELECT * FROM CUSTOMER_PAYMENT;
/
--CUSTOMER_PAYMENT SEQUENCE
----VENDOR-SEQUENCE
CREATE SEQUENCE CUST_PAY
INCREMENT BY 1
START WITH 1
MAXVALUE 20
MINVALUE 1
NOCYCLE
NOCACHE;
/
DROP SEQUENCE CUST_PAY;
/
CREATE TABLE VENDOR_PAYMENT
(
VP_ID NUMBER PRIMARY KEY,
VO_ID NUMBER,
CONSTRAINT V_PAY FOREIGN KEY (VO_ID) REFERENCES VENDOR_ORDER (VO_ID),
PAYMENT_MODE VARCHAR2(20),
VP_DATE DATE
);
/
--VENDOR_PAYMENT SEQUENCE
----VENDOR-SEQUENCE
CREATE SEQUENCE VEND_PAY
INCREMENT BY 1
START WITH 1
MAXVALUE 20
MINVALUE 1
NOCYCLE
NOCACHE;
/
DROP SEQUENCE VEND_PAY;
/
CREATE TABLE VENDOR_DETAILS
(
VO_ID NUMBER,
CONSTRAINT O_D FOREIGN KEY (VO_ID) REFERENCES VENDOR_ORDER (VO_ID),
WINE_NAME VARCHAR2(50),
CONSTRAINT ORD FOREIGN KEY (WINE_NAME) REFERENCES PRODUCT_STOCK (WINE_NAME),
VD_ID NUMBER,
CONSTRAINT ORD_D FOREIGN KEY (VD_ID) REFERENCES VENDOR (VD_ID),
QUANTITY NUMBER CHECK(QUANTITY>0),
PRICE NUMBER
);
/
SELECT * FROM VENDOR_DETAILS;
/
----VENDOR-SEQUENCE
CREATE SEQUENCE VEND_DETAILS
INCREMENT BY 1
START WITH 1
MAXVALUE 20
MINVALUE 1
NOCYCLE
NOCACHE;
/
DROP SEQUENCE VEND_DETAILS;
















